# Generated by Django 3.0.4 on 2020-03-24 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('user_type', models.BooleanField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Model',
        ),
        migrations.RemoveField(
            model_name='issue_model',
            name='affected_user',
        ),
        migrations.RemoveField(
            model_name='issue_model',
            name='assigned_user',
        ),
        migrations.AddField(
            model_name='issue_model',
            name='assigned_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue_model',
            name='affected_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Profile'),
            preserve_default=False,
        ),
    ]
