# Generated by Django 3.0.5 on 2020-04-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_model',
            name='issue_type',
            field=models.CharField(max_length=240),
        ),
    ]
