# Generated by Django 3.0.3 on 2020-03-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=240)),
                ('issue_type', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('assigned_user', models.CharField(max_length=50)),
                ('affected_user', models.CharField(max_length=50)),
                ('is_solved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('user_type', models.BooleanField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
